### ISSUE TITLE
release modbus cli v1.1.0

### ISSUE THREAD

**Issue by frzifus** [grid-x/modbus#63]
The release [1.0 ](https://github.com/grid-x/modbus/releases/tag/v1.0)is quite old. In the meantime more than 30 changes have been implemented. We should provide a version v1.1. WDYT?

Would be nice if it includes https://github.com/grid-x/modbus/pull/62.

**Comment by tretmar** [comment]
@frzifus yes, I totally agree with you. I actually wanted to finish up #62 and then make a release ;)

**Comment by tretmar** [comment]
@frzifus it's finally done 💪 Check out https://github.com/grid-x/modbus/releases/tag/v1.2
